name: Build and Publish S3 File Manager Docker Image

on:
  release:
    types:
    - created
    - edited

jobs:
  build-and-push-s3fm-image:
    name: Build and Push S3 File Manager Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_REPO_S3FM }}:${{ github.event.release.tag_name }}
